/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:29.0-jre")

    // For http requests
    implementation("com.squareup.okhttp3:okhttp:4.9.0")

    // Json serializing
    implementation("com.google.code.gson:gson:2.8.6")

    // webs scraping
    api("it.skrape:skrapeit-core:1.0.0-alpha6")

    // Junit 5 fo testing
    testImplementation("org.junit.jupiter:junit-jupiter:5.4.2")

}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}


publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "no.exotech"
            artifactId = "pricefetcher"
            version = "v0.1.1-alpha"
            from(components["java"])
        }
    }
}

group = "no.exotech"
version = "v0.1.1-alpha"
